insert into users (name, password, email, postal_code, latitude, longtitude) values ('Barret Flecknell', 'dg60U08r', 'bflecknell0@craigslist.org', null, -7.466569, 112.4500076);
insert into users (name, password, email, postal_code, latitude, longtitude) values ('Benito Angrave', 'zmopqVBgVdxC', 'bangrave1@rediff.com', null, null, null);
insert into users (name, password, email, postal_code, latitude, longtitude) values ('Kevin', 'qL5U2tPzHa', 'lbenezet2@ibm.com', null, null, null);
insert into users (name, password, email, postal_code, latitude, longtitude) values ('Linell Trood', 'OB101TZeeG', 'ltrood3@cmu.edu', '4939', null, null);
insert into users (name, password, email, postal_code, latitude, longtitude) values ('Anett Geydon', 'tW0jzj4ItBR', 'ageydon4@51.la', null, null, null);
insert into users (name, password, email, postal_code, latitude, longtitude) values ('Kelley Cammock', 'qeBCfG5g', 'kcammock5@freewebs.com', null, null, null);
insert into users (name, password, email, postal_code, latitude, longtitude) values ('Alexandr Ishchenko', 'GFqzFLj', 'aishchenko6@phpbb.com', null, null, null);
insert into users (name, password, email, postal_code, latitude, longtitude) values ('Astrid Boosey', 'YpTnHf', 'aboosey7@buzzfeed.com', null, 13.871805, 101.052868);
insert into users (name, password, email, postal_code, latitude, longtitude) values ('Hayley Allery', '0KTLLSviAI', 'hallery8@opera.com', null, null, null);
insert into users (name, password, email, postal_code, latitude, longtitude) values ('Massimiliano Notti', '7yDOT4J3slO', 'mnotti9@phpbb.com', null, null, null);
